name: vectra
description: "A comprehensive learning management system for efficiently managing institute data, integrating complex logic with an intuitive, user-friendly interface."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.

version: 1.0.0+1

environment:
  sdk: ^3.5.1

# `flutter pub upgrade --major-versions`
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # Firebase Integration
  firebase_core: ^3.3.0 # Core Firebase utilities
  firebase_auth: ^5.1.4 # Firebase Authentication
  cloud_firestore: ^5.2.1 # Firestore Database
  firebase_storage: ^12.1.3 # Firebase Cloud Storage
  firebase_messaging: ^15.0.4 # Firebase Cloud Messaging
  firebase_analytics: ^11.2.1 # Firebase Analytics
  firebase_crashlytics: ^4.0.4 # Crashlytics for error reporting
  firebase_performance: ^0.10.0+4 # Performance monitoring

  # Local Storage Solutions
  shared_preferences: ^2.2.2 # Simple key-value storage
  hive: ^2.2.3 # Lightweight NoSQL database

  # State Management
  provider: ^6.1.1 # State management with Provider
  flutter_riverpod: ^2.4.8 # State management with Riverpod

  # UI/Animation Enhancements
  shimmer: ^3.0.0 # Shimmer loading animations
  confetti: ^0.7.0 # Confetti effects for celebrations
  lottie: ^3.0.0 # Lottie animations

  # Functional Dependencies
  excel: ^4.0.2 # Excel file handling
  image_picker: ^1.0.4 # Image picker utility
  share_plus: ^10.0.0 # File sharing utility
  path_provider: ^2.1.1 # Access to file paths
  file_picker: ^8.0.7 # File picker utility
  open_file: ^3.3.2 # Open files from the app

  # UI Widgets and Enhancements
  calendar_date_picker2: ^1.1.5 # Date picker utility
  dotted_border: ^2.1.0 # Dotted borders for UI elements
  syncfusion_flutter_charts: ^26.2.10 # Advanced charts and graphs
  flutter_switch: ^0.3.2 # Custom switch widgets
  flutter_rating_stars: ^1.0.3+4 # Rating stars widget
  video_player: ^2.9.1 # Video playback utility
  audio_waveforms: ^1.0.5 # Audio waveforms display
  linked_scroll_controller: ^0.2.0 # Linked scrolling between multiple scroll views
  material_symbols_icons: ^4.2777.1 # Material symbols for icons

  # Networking and Data Handling
  dio: ^5.4.0 # Powerful HTTP client
  rxdart: ^0.28.0 # Reactive programming with streams
  intl: ^0.19.0 # Internationalization utilities
  csv: ^6.0.0 # CSV file handling

  # Image and Media Handling
  cached_network_image: ^3.3.1 # Cached network images
  icons_launcher: ^2.1.7 # Custom launcher icons
  firebase_vertexai: ^0.2.2+4 # Firebase Vertex AI integration for ML

  # Connectivity and Utilities
  connectivity_plus: ^6.0.4 # Connectivity status and events
  url_launcher: ^6.3.0 # Launch URLs in external applications

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

# Generates app icon
icons_launcher:
  # Path to the main image used for generating app icons
  image_path: "assets/images/logo.png"

  platforms:
    android:
      enable: true
    ios:
      enable: true

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gif/
    - assets/json/

  fonts:
    - family: IstokWeb
      fonts:
        - asset: assets/fonts/Istok_Web/IstokWeb-Regular.ttf
        - asset: assets/fonts/Istok_Web/IstokWeb-Bold.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 800
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 500
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 400
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 200

    - family: Nunito
      fonts:
        # - asset: assets/fonts/Nunito/Nunito-Black.ttf
        #   weight: 900
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-VariableFont_wght.ttf

    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather/Merriweather-Black.ttf
          weight: 900
        - asset: assets/fonts/Merriweather/Merriweather-Bold.ttf
          weight: 800
        - asset: assets/fonts/Merriweather/Merriweather-Regular.ttf
          weight: 500
        - asset: assets/fonts/Merriweather/Merriweather-Light.ttf
          weight: 400
  #
